[package]
name = "simon"
version = "0.0.0"
authors = []

[dependencies]
rand = "0.5.0-pre.1"
rand_derive = "0.3"
reqwest = "0.8"
dotenv = "0.11"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
hyper = "0.11"

[dependencies.conrod]
version = "0.58.0"
features = ["winit", "glium"]
